name: ci

on:
  push:
    paths:
      - "**.for"
      - "**.py"
      - "CMakeLists.txt"

env:
  CMAKE_GENERATOR: Ninja

jobs:

  core:
    timeout-minutes: 3

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --test-dir build -V
